### ISSUE TITLE
SQL-Error: auftraege.php

### ISSUE THREAD

**Issue by larsmuenchhagen** [JohannMuenchhagen/Auftragsverwaltung#1]
Seite funktioniert nicht. Beim Versuch die Datei mit der aktion 'read' aufzurufen, wird ein SQL-STATE-ERROR geworfen.
Unbedingt und schnell beheben. Alle Funktionen testen. Frontend wartet auf Backend.

**Comment by JohannMuenchhagen** [comment]
funktioniert Fehler frei
