### ISSUE TITLE
Allgemeiner Fehler: produkte.php

### ISSUE THREAD

**Issue by larsmuenchhagen** [JohannMuenchhagen/Auftragsverwaltung#3]
Seite funktioniert nicht. Beim Versuch die Datei mit der aktion 'read' aufzurufen, wird nichts ausgegeben, nicht einmal eine Fehlermeldung.
Unbedingt und schnell beheben. Alle Funktionen testen. Frontend wartet auf Backend.

**Comment by JohannMuenchhagen** [comment]
behoben
