### ISSUE TITLE
produkte.php Update funktioniert nicht -> SQL-ERROR

### ISSUE THREAD

**Issue by larsmuenchhagen** [JohannMuenchhagen/Auftragsverwaltung#5]
Fehlermeldung: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'Preis' at row 1

übergebene URL: produkte.php?aktion=update&produktnummer=7&name=%22Super%20Teuer%22&bezeichnung=teures%20Zeug&kategorie=Luxus&preis=1234567890.99lagerbestand=2

preis ist float

**Comment by JohannMuenchhagen** [comment]
behoben
