### ISSUE TITLE
Speichern ohne Funktion

### ISSUE THREAD

**Issue by JohannMuenchhagen** [JohannMuenchhagen/Auftragsverwaltung#7]
Bei dem Anlegen eines Auftrages wird die Anweisung zum Speichern nicht ausgeführt

**Comment by larsmuenchhagen** [comment]
gesendete daten an auftraege.php: ?aktion=create&auftragNeuData={"kundennummer":"3","status":"1","eingangsdatum":"2022-05-22","lieferdatum":"2022-05-22","gesamtpreis":"1.00"}&auftragProduktData=[{"Produktnummer":"1","Name":"Prod_Name_A","Bezeichnung":"Prod_Bez_A","Kategorie":"Prod_Kat_A","Preis":"1","Lagerbestand":"1","Anzahl":"1"}]
antwort api: {"Error":"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'Kundennummer' cannot be null"}

**Comment by larsmuenchhagen** [comment]
scheint api-fehler

**Comment by JohannMuenchhagen** [comment]
Fehler ist behoben
